---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kubesage-secrets
  namespace: dev
spec:
  encryptedData:
    anthropic-api-key: AgClARygmJgFqVEzuQvJXQxiABpAh7KenCi1mbTMQJrrEYKVuE2WmUGVFhtsdcbkexkvz/k8p1rO2hfEWo+27/xOW27Nwj8DMOsbjfCN0yvyc+VsIsZ/+Xiv9QlRecwdo+/oeaLbYZFzIXwdj08Dhiy6JUllrFVgnPs/M07aCaWedgBvpJOCPYiS9rGgZRoRpwGM3qigQmZPtCII6vnGPPOIBtMNICNaH/YQmTgrGRImvXEtZZSDwl9RlkMqTcxets/gHfwIcaxKFZWidlNGRiINqFr7B6k6l7v5sxIr0jkudXgCriUSiDfpQiqroCp/33sRz0xspU6JswB65gcKK+CoiqfxTOQstYIB4GM5pcNIBVnPH8fluDVQXWaPscSKFRM56AG4AKVdcW9UWXRf+FAgGnbs8vnv9bxMjyz7EfefgT0pRBIV2tG73vchSZ1kRrfBGt3HGM/8UiZyE1fsiVJmhLF/mGOMzjrl4SA0xwv+ow6WI46OcCkRjeJrpyVXmSwSv2m5cR/UOjTg/eQfSOpBbZ2KISKKuTjjK3Ik+wTl52R4yHmc5d7wc0OTQ2E/ex5B28uHbK+0ts/tRTmixOrz+jyUDM4e7sqOj0aUa+5KHcKhzi3MnHJzA638BIglk2fJ0qAnRyyb/RuS5Hks2WzOF5rfH5xV2HdVhXZtyUqXN2hOta+Q5o1y2TJvvVWOtAU2uk7gRIiql1ACpALa94HVzYaNbfhNpOQ5Vg2FIyZ84pZKtAKOn7Ju0slljpuF8fTJf+GkBDHV5/s7/BI92gu+rLfBkZ4JBQvQZIL0Dcu7SjI7GSkmghgfx0R3o/dAX+Ptg83IMqi2kiwKlL4=
  template:
    metadata:
      name: kubesage-secrets
      namespace: dev
