apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesage
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubesage
  template:
    metadata:
      labels:
        app: kubesage
    spec:
      containers:
      - name: kubesage
        image: aysebeyaz/kubesage:v1.0.0
        ports:
        - containerPort: 8501
        env:
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: kubesage-secrets
              key: anthropic-api-key
