apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubesage-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/b-beyaz/gitops-repo.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
